name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies for backend
        run: npm install
        
      - name: Install dependencies for frontend
        run: npm --prefix /frontend install

      - name: Run the tests for frontend
        run: npm --prefix /frontend test
        
      - name: Build the frontend
        run: npm --prefix /frontend run build
  
